services:
  influxdb:
    image: influxdb:2.7
    restart: unless-stopped
    ports:
      - "${INFLUXDB_PORT:-8086}:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: bomba888
      DOCKER_INFLUXDB_INIT_ORG: groep4
      DOCKER_INFLUXDB_INIT_BUCKET: sensordata
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mF0B9oNC8xw5l1o_yw3asTWLtIhmGmk2WdJHioLG627A1IqmsgXnZuc7GmNgzzMMplAry7O8EzUFVL9EdKyalQ==
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - cloudnet

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports: 
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - cloudnet

  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: bomba888
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb
    networks:
      - cloudnet

  nodered:
    build: ./nodered
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - nodered-data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - influxdb
    networks:
      - cloudnet

  sensor-sim:
    build: ./sensor-sim
    restart: unless-stopped
    environment:
      MQTT_HOST: host.docker.internal
      MQTT_PORT: 1883
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - cloudnet

networks:
  cloudnet:
    driver: bridge

volumes: 
  influxdb-data:
  nodered-data:
  portainer_data:
  grafana-data: